### ISSUE TITLE
In android we can implement with reanimated?

### ISSUE THREAD

**Issue by eduardoborges** [nandorojo/burnt#2]
Bring more performance to the library, buuut... reanimated must be a lib dep. It's a problem?

**Comment by nandorojo** [comment]
I think a better solution would be to use a native Android toast. https://developer.android.com/guide/topics/ui/notifiers/toasts

**Comment by fobos531** [comment]
> I think a better solution would be to use a native Android toast. [developer.android.com/guide/topics/ui/notifiers/toasts](https://developer.android.com/guide/topics/ui/notifiers/toasts)

@nandorojo Hey, I agree that the native toast is better in this case. However, the "vanilla" Android toast has an extremely simple API. Since we're using a 3rd party library for iOS, maybe we could do the same for Android to achieve higher feature parity between the platforms. Have you come across an Android notification library that you like?

**Comment by nandorojo** [comment]
I haven't, but I'm open to suggestions! There's also the Android Snackbar

**Comment by nandorojo** [comment]
is there an english version of the docs?

**Comment by fobos531** [comment]
@nandorojo I can't believe I didn't think of it before, but React Native core actually has a ToastAndroid API built in - maybe that could be used until a more feature-fledged alternative is found & implemented?

**Comment by nandorojo** [comment]
Oh, cool yeah that works.

**Comment by nandorojo** [comment]
Burnt `0.8` now uses `ToastAndroid` to add Android support.

```sh
yarn add burnt
```

`Burnt.alert()` falls back to `Burnt.toast()` on Android since there is no equivalent.
